# Generated by Django 2.0.2 on 2023-04-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('climate', models.CharField(max_length=200)),
                ('soil', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
                ('height', models.FloatField()),
            ],
        ),
    ]
