# Generated by Django 2.0.2 on 2023-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
